spring.application.name=demo03

spring.datasource.url=jdbc:mysql://localhost:3306/tecsup_delivery?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root2026!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect